In [1]:
import numpy as np

In [2]:
a = np.array([5,6,9])

In [3]:
a[0]

5

In [4]:
a[2]

9

In [12]:
a.ndim

1

In [10]:
b = np.array([[1,2],[3,4],[5,6]])

In [11]:
b.ndim

2

In [13]:
a.dtype

dtype('int64')

In [14]:
a.itemsize

8

In [16]:
b = np.array([[1,2],[3,4],[5,6]], dtype = np.float)

In [17]:
b.dtype

dtype('float64')

In [18]:
b.itemsize

8

In [19]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [20]:
b.size

6

In [21]:
b.shape

(3, 2)

In [22]:
b = np.array([[1,2],[3,4],[5,6]], dtype = complex)

In [23]:
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
l = range(5)

In [27]:
l

[0, 1, 2, 3, 4]

In [28]:
l[1]

1

In [29]:
np.arange(1,5)

array([1, 2, 3, 4])

In [31]:
np.arange(1,5,2)

array([1, 3])

In [33]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [35]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [38]:
c = np.array([[1,2],[3,4],[5,6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
c.shape

(3, 2)

In [40]:
c.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
c.ravel()

array([1, 2, 3, 4, 5, 6])

In [43]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
c.min()

1

In [45]:
c.max()

6

In [46]:
c.sum()

21

In [47]:
c.sum(axis=0)

array([ 9, 12])

In [48]:
c.sum(axis=1)

array([ 3,  7, 11])

In [49]:
np.sqrt(c)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [50]:
np.std(c)

1.707825127659933

In [53]:
x = np.array([[1,2],[3,4]])

In [54]:
x

array([[1, 2],
       [3, 4]])

In [55]:
y = np.array([[5,6],[7,8]])

In [56]:
y

array([[5, 6],
       [7, 8]])

In [57]:
x+y

array([[ 6,  8],
       [10, 12]])

In [58]:
x*y

array([[ 5, 12],
       [21, 32]])

In [66]:
x.dot(y)

array([[19, 22],
       [43, 50]])